export const defaultCategories = [
  { type: 'entrada', name: 'Salário' },
  { type: 'entrada', name: 'Comissão' },
  { type: 'entrada', name: 'Vale' },
  { type: 'entrada', name: 'Benefício' },
  { type: 'entrada', name: 'Outros' },
  { type: 'saida', name: 'Aluguel' },
  { type: 'saida', name: 'Financiamento' },
  { type: 'saida', name: 'Condomínio' },
  { type: 'saida', name: 'Conta de luz' },
  { type: 'saida', name: 'Conta de água' },
  { type: 'saida', name: 'Internet' },
  { type: 'saida', name: 'Outros' },
  { type: 'diario', name: 'Mercado' },
  { type: 'diario', name: 'Transporte' },
  { type: 'diario', name: 'Farmácia' },
  { type: 'diario', name: 'Lanche' },
  { type: 'diario', name: 'Restaurante' },
  { type: 'diario', name: 'Outros' },
  { type: 'economia', name: 'Reserva de emergência' },
  { type: 'economia', name: 'Investimento' },
  { type: 'economia', name: 'Outros' },
  { type: 'cartao', name: 'Compras' },
  { type: 'cartao', name: 'Assinaturas' },
  { type: 'cartao', name: 'Viagem' },
  { type: 'cartao', name: 'Outros' },
]
