-- Store the scheduled slot separately from the effective date so a single
-- occurrence can be moved without changing the cadence of an open series.
ALTER TABLE "transactions"
  ADD COLUMN "recurrence_open_ended" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "recurrence_anchor_date" DATE,
  ADD COLUMN "recurrence_slot_date" DATE;

-- Backfill existing series metadata. Older monthly open series were capped at
-- December, so series that started earlier in the same year and ended there
-- are treated as open-ended. Their old schema did not retain the selected limit.
WITH series_bounds AS (
  SELECT
    "series_id",
    MIN("date") AS first_date,
    MAX("date") AS last_date,
    COUNT(*) AS occurrence_count,
    BOOL_AND("recurrence" = 'monthly') AS is_monthly
  FROM "transactions"
  WHERE "series_id" IS NOT NULL
    AND "recurrence" <> 'never'
  GROUP BY "series_id"
),
series_metadata AS (
  SELECT
    "series_id",
    MIN("date") AS anchor_date
  FROM "transactions"
  WHERE "series_id" IS NOT NULL
    AND "recurrence" <> 'never'
  GROUP BY "series_id"
)
UPDATE "transactions" AS tx
SET
  "recurrence_anchor_date" = metadata.anchor_date,
  "recurrence_slot_date" = tx."date",
  "recurrence_open_ended" = (
    bounds.is_monthly
    AND bounds.occurrence_count > 1
    AND EXTRACT(YEAR FROM bounds.first_date) = EXTRACT(YEAR FROM bounds.last_date)
    AND EXTRACT(MONTH FROM bounds.last_date) = 12
  )
FROM series_metadata AS metadata
JOIN series_bounds AS bounds USING ("series_id")
WHERE tx."series_id" = metadata."series_id";

-- Older createMany paths could leave a category off some copies. Reuse the
-- earliest categorized occurrence in each series to restore that reference.
WITH series_categories AS (
  SELECT DISTINCT ON ("series_id")
    "series_id",
    "category_id"
  FROM "transactions"
  WHERE "series_id" IS NOT NULL
    AND "category_id" IS NOT NULL
  ORDER BY "series_id", "date" ASC, "created_at" ASC
)
UPDATE "transactions" AS tx
SET "category_id" = series_categories."category_id"
FROM series_categories
WHERE tx."series_id" = series_categories."series_id"
  AND tx."category_id" IS NULL;

-- Preserve the first row if legacy edits moved multiple occurrences onto the
-- same date. New scheduled slots are unique; unmarked legacy copies can be
-- regenerated by an open series when that month is next viewed.
WITH duplicate_slots AS (
  SELECT
    "id",
    ROW_NUMBER() OVER (
      PARTITION BY "series_id", "recurrence_slot_date"
      ORDER BY "created_at", "id"
    ) AS slot_position
  FROM "transactions"
  WHERE "series_id" IS NOT NULL
    AND "recurrence_slot_date" IS NOT NULL
)
UPDATE "transactions" AS tx
SET "recurrence_slot_date" = NULL
FROM duplicate_slots
WHERE tx."id" = duplicate_slots."id"
  AND duplicate_slots.slot_position > 1;

CREATE UNIQUE INDEX "transactions_series_id_recurrence_slot_date_key"
  ON "transactions"("series_id", "recurrence_slot_date");
CREATE INDEX "transactions_user_recurrence_open_anchor_idx"
  ON "transactions"("user_id", "recurrence_open_ended", "recurrence_anchor_date");

CREATE TABLE "recurrence_exceptions" (
  "id" TEXT NOT NULL,
  "user_id" TEXT NOT NULL,
  "series_id" UUID NOT NULL,
  "slot_date" DATE NOT NULL,
  CONSTRAINT "recurrence_exceptions_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "recurrence_exceptions_series_id_slot_date_key"
  ON "recurrence_exceptions"("series_id", "slot_date");
CREATE INDEX "recurrence_exceptions_user_id_series_id_idx"
  ON "recurrence_exceptions"("user_id", "series_id");

ALTER TABLE "recurrence_exceptions"
  ADD CONSTRAINT "recurrence_exceptions_user_id_fkey"
  FOREIGN KEY ("user_id") REFERENCES "users"("id")
  ON DELETE RESTRICT ON UPDATE CASCADE;
